[package]
name = "zellij-sessionizer"
version = "0.4.0"
edition = "2021"
description = "Zellij plugin to create sessions based on folder names"
license = "MIT"

[dependencies]
zellij-tile = "0.40.1"
nucleo-matcher = "0.3.1"
